import { User, Team, Season, Player, PlayerStats, SeasonAward } from './types';

export const mockTeams: Team[] = [
  {
    id: 'team-1',
    name: 'Los Angeles Lakers',
    primary_color: '#552583',
    secondary_color: '#FDB927',
  },
  {
    id: 'team-2',
    name: 'Boston Celtics',
    primary_color: '#007A33',
    secondary_color: '#BA9653',
  },
];

export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'player1@example.com',
    display_name: 'Player One',
    created_at: new Date().toISOString(),
  },
  {
    id: 'user-2',
    email: 'player2@example.com',
    display_name: 'Player Two',
    created_at: new Date().toISOString(),
  },
];

export const mockSeason: Season = {
  id: 'season-2024-25',
  year_start: 2024,
  year_end: 2025,
  playoff_tree: {
    round1: [
      { 
        id: 'series-lakers-warriors',
        team1: 'Los Angeles Lakers', 
        team2: 'Golden State Warriors', 
        winner: 'Los Angeles Lakers',
        team1Wins: 4,
        team2Wins: 2,
      },
      { 
        id: 'series-celtics-heat',
        team1: 'Boston Celtics', 
        team2: 'Miami Heat', 
        winner: 'Boston Celtics',
        team1Wins: 4,
        team2Wins: 1,
      },
      {
        id: 'series-suns-clippers',
        team1: 'Phoenix Suns',
        team2: 'LA Clippers',
        winner: 'Phoenix Suns',
        team1Wins: 4,
        team2Wins: 3,
      },
      {
        id: 'series-bucks-knicks',
        team1: 'Milwaukee Bucks',
        team2: 'New York Knicks',
        winner: 'Milwaukee Bucks',
        team1Wins: 4,
        team2Wins: 0,
      },
    ],
    round2: [
      { 
        id: 'series-lakers-suns',
        team1: 'Los Angeles Lakers', 
        team2: 'Phoenix Suns', 
        winner: null,
        team1Wins: 2,
        team2Wins: 1,
      },
      { 
        id: 'series-celtics-bucks',
        team1: 'Boston Celtics', 
        team2: 'Milwaukee Bucks', 
        winner: null,
        team1Wins: 1,
        team2Wins: 2,
      },
    ],
  },
  created_at: new Date().toISOString(),
};

export const mockPlayers: Player[] = [
  {
    id: 'player-1',
    user_id: 'user-1',
    player_name: 'Ace Baller',
    position: 'PG',
    height: 75,
    weight: 190,
    archetype: 'Playmaking Shot Creator',
    team_id: 'team-1',
    career_highs: {
      points: 52,
      rebounds: 12,
      assists: 18,
      steals: 6,
      blocks: 3,
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'player-2',
    user_id: 'user-2',
    player_name: 'Dunk Master',
    position: 'SF',
    height: 80,
    weight: 220,
    archetype: 'Two-Way Slasher',
    team_id: 'team-2',
    career_highs: {
      points: 48,
      rebounds: 15,
      assists: 10,
      steals: 5,
      blocks: 7,
    },
    created_at: new Date().toISOString(),
  },
];

export const mockStats: PlayerStats[] = [
  // Player 1 games
  {
    id: 'stat-1-1',
    player_id: 'player-1',
    season_id: 'season-2024-25',
    opponent_team_id: 'team-2',
    opponent_team_name: 'Boston Celtics',
    is_home: true,
    stats: {
      points: 28,
      rebounds: 5,
      assists: 12,
      steals: 2,
      blocks: 0,
      turnovers: 3,
      minutes: 36,
      fg_made: 11,
      fg_attempted: 20,
      threes_made: 4,
      threes_attempted: 8,
    },
    is_playoff_game: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'stat-1-2',
    player_id: 'player-1',
    season_id: 'season-2024-25',
    opponent_team_id: 'team-2',
    opponent_team_name: 'Boston Celtics',
    is_home: false,
    stats: {
      points: 35,
      rebounds: 7,
      assists: 15,
      steals: 3,
      blocks: 1,
      turnovers: 2,
      minutes: 38,
      fg_made: 14,
      fg_attempted: 24,
      threes_made: 5,
      threes_attempted: 10,
    },
    is_playoff_game: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'stat-1-3',
    player_id: 'player-1',
    season_id: 'season-2024-25',
    opponent_team_name: 'Phoenix Suns',
    is_home: true,
    stats: {
      points: 22,
      rebounds: 4,
      assists: 8,
      steals: 1,
      blocks: 0,
      turnovers: 4,
      minutes: 32,
      fg_made: 9,
      fg_attempted: 18,
      threes_made: 2,
      threes_attempted: 6,
    },
    is_playoff_game: true,
    playoff_series_id: 'series-lakers-suns',
    created_at: new Date().toISOString(),
  },
  // Player 2 games
  {
    id: 'stat-2-1',
    player_id: 'player-2',
    season_id: 'season-2024-25',
    opponent_team_id: 'team-1',
    opponent_team_name: 'Los Angeles Lakers',
    is_home: false,
    stats: {
      points: 32,
      rebounds: 10,
      assists: 6,
      steals: 2,
      blocks: 3,
      turnovers: 2,
      minutes: 37,
      fg_made: 13,
      fg_attempted: 22,
      threes_made: 3,
      threes_attempted: 7,
    },
    is_playoff_game: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'stat-2-2',
    player_id: 'player-2',
    season_id: 'season-2024-25',
    opponent_team_id: 'team-1',
    opponent_team_name: 'Los Angeles Lakers',
    is_home: true,
    stats: {
      points: 27,
      rebounds: 12,
      assists: 8,
      steals: 4,
      blocks: 2,
      turnovers: 3,
      minutes: 35,
      fg_made: 11,
      fg_attempted: 19,
      threes_made: 2,
      threes_attempted: 5,
    },
    is_playoff_game: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'stat-2-3',
    player_id: 'player-2',
    season_id: 'season-2024-25',
    opponent_team_name: 'Miami Heat',
    is_home: true,
    stats: {
      points: 41,
      rebounds: 14,
      assists: 7,
      steals: 3,
      blocks: 4,
      turnovers: 1,
      minutes: 40,
      fg_made: 16,
      fg_attempted: 26,
      threes_made: 4,
      threes_attempted: 9,
    },
    is_playoff_game: true,
    playoff_series_id: 'series-celtics-heat',
    created_at: new Date().toISOString(),
  },
];

export const mockAwards: SeasonAward[] = [
  {
    id: 'award-1',
    player_id: 'player-1',
    season_id: 'season-2024-25',
    award_name: 'Player of the Week',
    created_at: new Date().toISOString(),
  },
  {
    id: 'award-2',
    player_id: 'player-2',
    season_id: 'season-2024-25',
    award_name: 'Defensive Player of the Week',
    created_at: new Date().toISOString(),
  },
];

